name: Tests

on:
  pull_request:
  push:
    branches: master

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: python3 -m pip install -U pip -r requirements.txt
      - name: Build Docs
        run: sphinx-build -n -W -q -b html -d _build/doctrees . _build/html
